### 패키지

In [1]:
import numpy as np

## Numpy 배열 

배열의 모든 요소가 같은 타입이어야 함  
타입이 일치하지 않을 경우 가능한 상위 타입을 취함 (upcasting)

In [2]:
ans1 = "전부 문자열로 바뀐다."
ans2 = "dtype"
ans3 = "float32"
ans4 = "ndim"
ans5 = "rank"
ans6 = 1

In [3]:
arr = [3.14, 2, 5, 3]
n_arr = np.array(arr)
print(arr)
print(type(arr))
print(n_arr)
print(type(n_arr))
print(n_arr.dtype) # float64

[3.14, 2, 5, 3]
<class 'list'>
[3.14 2.   5.   3.  ]
<class 'numpy.ndarray'>
float64


In [4]:
# 아래와 같은 경우에는 어떻게 될까?? 손으로 써보고 숨김 결과 확인 // o로 펼치고 숨길 수 있음 
arr = ['3.14', 2., 5, 3]
n_arr = np.array(arr)

print(arr, type(arr), n_arr, type(n_arr), n_arr.dtype)
print(ans1)

['3.14', 2.0, 5, 3] <class 'list'> ['3.14' '2.0' '5' '3'] <class 'numpy.ndarray'> <U32
전부 문자열로 바뀐다.


In [5]:
print(f"명시적으로 데이터 타입을 설정하기 위해서는 {ans2} 사용")

명시적으로 데이터 타입을 설정하기 위해서는 dtype 사용


In [7]:
arr = [1, 4, 2, 5, 3]
n_arr = np.array(arr, dtype="float32") # ans3에 들어갈 올바른 답 찾기 
print(arr)
print(type(arr))
print(n_arr)
print(type(n_arr))

[1, 4, 2, 5, 3]
<class 'list'>
[1. 4. 2. 5. 3.]
<class 'numpy.ndarray'>


In [ ]:
print(ans3)

float32


### 넘파이 배열의 속성 

In [ ]:
print(f"배열의 차원을 {ans4} 속성을 통해 알 수 있다.")

배열의 차원을 ndim 속성을 통해 알 수 있다.


In [ ]:
print(f"차원의 수를 {ans5}를 통해 알 수 있다.")

차원의 수를 rank를 통해 알 수 있다.


In [ ]:
nums = np.array([1, 4, 2, 5, 3])
print(nums)
print(nums.ndim)
print(nums.shape)
print(nums.shape)
print(len(nums.shape))
print(nums.size)

[1 4 2 5 3]
1
(5,)
(5,)
1
5


항목의 수를 구하기 위해서 len()함수를 사용할 경우 다차원 배열에서 문제 발생 

In [ ]:
mularr = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

print(len(mularr), mularr.shape, mularr.size) 
# len은 최상위 차원의 길이만 반환한다. 

2 (2, 3) 6


## 인덱싱/슬라이싱 

In [ ]:
nums = np.array([1, 4, 2, 5, 3])
print(nums[1])
print(nums[:3])
print(nums[2:4])

4
[1 4 2]
[2 5]


슬라이싱 : 
- 배열명[start:stop:step]
- 값이 지정되지 않은 경우 기본값 사용 
    - start = 0
    - stop = 차원의 크기
    - step = 1

In [ ]:
nums = np.array([1, 4, 2, 5, 3])
print(nums[::2]) # 맞춰보세요  0:0:2

[1 2 3]


### 2차원 배열 

1차원 리스트를 n개 가지고 있는 리스트 사용 

In [ ]:
nums = np.array([
    [1, 4, 2], 
    [7, 5, 3]
])
print(nums)
print(nums.ndim)
print(nums.shape)
print(len(nums.shape))
print(nums.size)

[[1 4 2]
 [7 5 3]]
2
(2, 3)
2
6


In [ ]:
print(nums)

[[1 4 2]
 [7 5 3]]


In [ ]:
print(nums[0][2], nums[0, 2])

2 2


In [ ]:
print(nums[0:1,])
print(nums[0:1, :])
print(nums[:, 1:2])
print(nums[1, 1:])
print(nums[0:, 1:])

[[1 4 2]]
[[1 4 2]]
[[4]
 [5]]
[5 3]
[[4 2]
 [5 3]]


슬라이싱을 할 경우 범위로 슬라이싱할 때와  
특정 행/열을 슬라이싱할 때의 결과가 다르다.  
같은 범위라도 인덱싱과 슬라이싱했을 때의 차원이 다르다는 것이다. 

In [ ]:
nums = np.array([[1, 4, 2], [7, 5, 3]])
# 아래 결과가 나오게 입력하세요.
print()
print()
print()
print()


5
[7 5]
[[2]
 [3]]
[[1 4]
 [7 5]]


In [ ]:
print(nums[1, 1])
print(nums[1, :2])
print(nums[:, 2:])
print(nums[:2, :2])

5
[7 5]
[[2]
 [3]]
[[1 4]
 [7 5]]


array 함수에 1개만 넣을 경우 어떻게 될까요?? 

In [ ]:
nums = np.array(3)
print(nums)
print(nums.ndim)
print(nums.shape)

3
0
()


### deep copy 

배열에 대한 검색/슬라이싱 결과는 참조만 할당  
- 기존 배열이 변경될 경우 값이 같이 변경됨 
- 독립적으로 사용해야 할 경우 copy() 함수 사용 

In [ ]:
nums = np.array([1, 4, 2, 5, 3])
ref = nums[1:4]
cpy = nums[1:4].copy()
ref[2] = 10
print(ref)
print(cpy)
print(nums)
print(id(nums[1]), id(ref[0]), id(cpy)) # 첫 원소의 주소가 동일하다 -> 메모리 주소만 갖다 준 거 

[ 4  2 10]
[4 2 5]
[ 1  4  2 10  3]
4689115984 4689115984 5105696080


### 내장 함수를 이용한 배열 생성 

- zeros(shape) : 모든 값이 0인 배열 생성 
- ones(shape) : 모든 값이 1인 배열 생성 
- full(shape, value) : 모든 값이 value인 배열 생성 
- shape => tuple값이여야 함 

In [ ]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((1, ), 7)
# 1차원 = (1,) != (1, 1) = 2차원

array([7])

- eye(size, k=n) : 
    - size * size인 단위행렬 생성 후 k만큼 이동 
- identity(size) : 
    - size * size인 단위행렬 생성 

In [ ]:
np.eye(3, k=1) # 1만큼 오른쪽으로 이동, 그러나 (2, 2)의 값은 다시 (2, 0)으로 오지 않는다. 

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random 함수 

- np.random.random(shape) : shape 형태의 0과 1 사이의 임의의 실수로 채운다. 
- np.random.randint(low, high, shape) : shape 형태의 low <= x< high 범위의 정수값으로 채운다. 
- np.random.normal(shape) : 정규분포를 따르는 난수 생성 

In [ ]:
np.random.random((2, 3))

array([[0.14165483, 0.02157615, 0.61358399],
       [0.82794905, 0.38346901, 0.4305981 ]])

In [ ]:
np.random.normal((2, 3))

array([2.14180844, 2.41203368])

In [ ]:
np.random.randint(1, 10, (2, 3))

array([[2, 9, 4],
       [3, 6, 8]])

### linspace  
- np.linspace(start, stop, num, endpoint, retstep) : start, stop까지의 같은 간격의 1차원 배열 생성 
- num : 1차원 numpy 배열 원소 개수 
- endpoint : end 포함여부 True / False로 구분 
- retstep : step 출력할 지 안 할지 True / False로 구분 

In [ ]:
print(np.linspace(0, 1, num=5, endpoint=True, retstep=True)) # tuple 형태 
print(np.linspace(0, 1, num=5, endpoint=True, retstep=True)[1])

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)
0.25


- np.arange(start, stop, step, dtype=??) : start부터 stop 전까지 step만큼 띄워서 배열 생성 

In [ ]:
np.arange(0, 12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 행렬 전환과 형태 변형 

- np.reshape(shape) : shape 튜플 만큼의 크기로 변형 
- 기존 배열과 새로운 배열의 아이템 수는 동일해야 함 => np.array.size 속성이 동일해야함 

In [8]:
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ABDE", "ADT"])
print(sap.size, sap.shape)
sap2d = sap.reshape(2, 4)
print(sap2d.size, sap2d.shape)

8 (8,)
8 (2, 4)


전치(Transpose)
- 함수 호출이 아닌 속성 T를 사용 

In [9]:
print(sap2d)
print(sap2d.T)
print(sap2d.shape, sap2d.T.shape)

[['MMM' 'ABT' 'ABBV' 'ACN']
 ['ACE' 'ATVI' 'ABDE' 'ADT']]
[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ABDE']
 ['ACN' 'ADT']]
(2, 4) (4, 2)


### 행열 전환과 형태 변형  
- `swapaxes(axis_1, axis_2)`
- 축1(axis_1)과 축2(axis_2)를 서로 맞바꿈 

In [10]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ABDE', 'ADT'],
      dtype='<U4')

In [11]:
sap2d = sap.reshape(2, 4)
print(sap2d)
print(sap2d.T)
print(sap2d.swapaxes(0, 1))

[['MMM' 'ABT' 'ABBV' 'ACN']
 ['ACE' 'ATVI' 'ABDE' 'ADT']]
[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ABDE']
 ['ACN' 'ADT']]
[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ABDE']
 ['ACN' 'ADT']]


In [12]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ABDE', 'ADT'],
      dtype='<U4')

In [14]:
sap3d = sap.reshape(2, 2, 2) # 2 * 2 * 2 = 8
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ABDE', 'ADT']]], dtype='<U4')

In [18]:
print(sap3d.swapaxes(1, 2))

[[['MMM' 'ABBV']
  ['ABT' 'ACN']]

 [['ACE' 'ABDE']
  ['ATVI' 'ADT']]]


In [19]:
print(sap3d.swapaxes(0, 1))

[[['MMM' 'ABT']
  ['ACE' 'ATVI']]

 [['ABBV' 'ACN']
  ['ABDE' 'ADT']]]


In [20]:
print(sap3d.swapaxes(0, 2))

[[['MMM' 'ACE']
  ['ABBV' 'ABDE']]

 [['ABT' 'ATVI']
  ['ACN' 'ADT']]]


In [21]:
print(sap3d.T) # swapaxes(0, 2)의 결과와 동일 

[[['MMM' 'ACE']
  ['ABBV' 'ABDE']]

 [['ABT' 'ATVI']
  ['ACN' 'ADT']]]


### numpy 배열의 연결 - concatenate 
- 파라미터 : 리스트 -> 몇 개를 순서대로 concatenate할 지 모르기 때문이다. 

In [23]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

[1 2 3 3 2 1]


In [24]:
z = np.array([4, 5, 6])
print(np.concatenate([x, y, z]))

[1 2 3 3 2 1 4 5 6]


1차원 배열끼리 concatenate은 axis 적용 안됨 

In [28]:
grid = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
print(np.concatenate([grid, grid])) # 가장 높은 차원 기준으로 추가 후 가장 바깥 리스트 추가 
print(grid.shape, np.concatenate([grid, grid]).shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(2, 3) (4, 3)


In [29]:
print(np.concatenate([grid, grid], axis=1)) # 2차원 이상일 때만 적용됨 

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
