### 패키지 

In [1]:
import numpy as np

### Numpy 배열의 연결 - vstack

In [2]:
x = np.array([9, 8, 7])
grid = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
print(np.vstack([x, grid]))

[[9 8 7]
 [1 2 3]
 [4 5 6]]


In [7]:
print(np.concatenate([x, grid], axis=0))
# 될 거 같은데 안된다. 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [8]:
y = np.array([
    [9], 
    [8]
])
grid = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
print(y.shape, grid.shape)
print(np.hstack([y, grid]))

(2, 1) (2, 3)
[[9 1 2 3]
 [8 4 5 6]]


### Numpy 배열의 분할 

- split()
- hsplit()
- vsplit()
- dsplit()

In [9]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # 0~ /3~ /5~ # 구분 : 언제 얼마나 나눌 지 몰라서 리스트 
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [21]:
grid = np.arange(16).reshape(4, 4)
print(grid)
upper, lower = np.split(grid, [2], axis=0)
print('--------------')
print(upper)
print('--------------')
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------
[[0 1 2 3]
 [4 5 6 7]]
--------------
[[ 8  9 10 11]
 [12 13 14 15]]


In [22]:
grid = np.arange(16).reshape(4, 4)
x, y = np.split(grid, [2], axis=1)
print(x)
print(y)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### numpy 배열 연산 

$$C = (F-32)*5/9$$

In [24]:
arr = [100, 80, 70, 90, 110]
[int((elem - 32) * 5/9) for elem in arr]

[37, 26, 21, 32, 43]

In [31]:
narr = np.array(arr)
print(np.trunc((narr - 32)*5/9))

[37. 26. 21. 32. 43.]


In [2]:
x = np.array([2, 4, 6, 8])
print(x)
print(x + 5)
print(x - 5)
print(x * 2)
print((x / 2).dtype) # 짝수여서 나머지가 없어도 float64로 일단 변환 

[2 4 6 8]
[ 7  9 11 13]
[-3 -1  1  3]
[ 4  8 12 16]
float64


### 브로드캐스팅 

In [3]:
a = np.array(4) # [4, 4, 4, 4]로 브로드캐스팅 
b = np.arange(1, 5) # [1, 2, 3, 4]
print(a + b)

[5 6 7 8]


In [4]:
a = np.arange(4) # [0, 1, 2, 3]
b = 5
a * b

array([ 0,  5, 10, 15])

In [6]:
noise = np.eye(4) + 0.01 * np.ones((4,))
print(np.eye(4))
print(np.ones(4,))
print(noise)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1. 1.]
[[1.01 0.01 0.01 0.01]
 [0.01 1.01 0.01 0.01]
 [0.01 0.01 1.01 0.01]
 [0.01 0.01 0.01 1.01]]


브로드캐스팅 규칙: 
1. 두 배열의 차원 수가 다르면, 더 적은 차원의 수를 가진 배열 형상의 앞쪽(왼쪽)을 1로 채운다. 
2. 두 배열의 형상이 어떤 차원에서 일치하지 않는다면, 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다. 
3. 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다. 

In [7]:
m = np.ones((3, 2))
a = np.arange(3)
print(m.shape, a.shape)

(3, 2) (3,)


In [8]:
m + a
# (3,2)+(3,) => (3,2) + (1,3) => (3,2)+(3,3) => error

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

### abs: 절댓값 함수 

In [9]:
a = np.array([-1, 0, 1])
print(abs(a))

[1 0 1]
