In [1]:
import numpy as np

In [2]:
grid = np.array([
    [1, 2, 3], 
    [4, 6, 2]
])
print(np.mean(grid, axis=1))

[2. 4.]


### Boolean 배열 

numpy 배열에는 산술연산자 외에 비교 연산자 활용 가능 

In [3]:
x = np.array([1, 2, 3, 4, 5])
print(x < 3)

[ True  True False False False]


In [4]:
print(x[x < 3])

[1 2]


In [5]:
rng = np.random.RandomState(0) # 난수 생성 

x = rng.randint(10, size=(3, 4))
print(x)
print(x < 6)


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In [8]:
x = rng.randint(10, size=(3, 4))
print(x)
print(np.count_nonzero(x < 6))
print(np.sum(x < 6))

[[4 3 0 3]
 [5 0 2 3]
 [8 1 3 3]]
11
11


In [9]:
print(np.sum(x < 6, axis=1))

[4 4 3]


In [10]:
print(np.any(x < 6, axis=1))

[ True  True  True]


python의 비트 연산자를 활용하여 여러 가지 조건을 결합 가능  
- &(and), |(or), ^(xor), ~(not)

In [11]:
x = np.array(
    [
        [5, 0, 3, 3], 
        [7, 9, 3, 5], 
        [2, 4, 7, 6]
    ]
)
print(np.sum((x >= 3) & (x < 6)))

6
